version: "3.8"

services:
  backend:
    build: backend
    restart: always
    container_name: backend
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000

  redis:
    image: redis/redis-stack:latest
    restart: always
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
  
  front:
    build:
      context: /frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
